cluster:
  name: rancher-desktop
cni:
  binPath: /usr/libexec/cni
gatewayAPI:
  enabled: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
  replicas: 1
routingMode: tunnel
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnelProtocol: vxlan
